server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    # Main location with allowed IPs
    location / {
        # allow 196.189.87.177;
        # allow 196.188.240.125;
        # allow 196.191.214.185;
        # allow 196.191.117.97;
        # deny all;

        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM handling
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to hidden files
    location ~ /\.ht {
        deny all;
    }

    # Optional stub status
    location /stub_status {
        stub_status;
        allow all;
    }
    location /build/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri =404;
}
}
